name: qmtools
channels:
  - pytorch
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pycuda
  - pytorch
  - pytorch-cuda=12.1
  - cuda
  - requests